### ISSUE TITLE
Please add an example workflows for ranges

### ISSUE THREAD

**Issue by ondrovic** [yolain/ComfyUI-Yolain-Workflows#10]
Would it be possible to add some workflows for float and int ranges?

Really looking to see if it's possible to use them when testing lora's

something kinda like this

![image](https://github.com/user-attachments/assets/de327f90-e000-4bae-93aa-33f80a6c3bf2)

**Comment by yolain** [comment]
> Would it be possible to add some workflows for float and int ranges?
> 
> Really looking to see if it's possible to use them when testing lora's
> 
> something kinda like this
> 
> ![image](https://private-user-images.githubusercontent.com/3682042/369193369-de327f90-e000-4bae-93aa-33f80a6c3bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTk0MDcsIm5iZiI6MTcyNjc5OTEwNywicGF0aCI6Ii8zNjgyMDQyLzM2OTE5MzM2OS1kZTMyN2Y5MC1lMDAwLTRiYWUtOTNhYS0zM2Y4MGE2YzNiZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMDIyNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzliM2Q2ZTc5ZDMxYWNlMzQ3OTcyMjc0N2VkZWYwMjg0YmE2MmRlNTllOTM5MTNiNzUzNGU0NWRmNjgxNzhmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XwhB2gUyed6IpyJNNIFXZlaEPLwbNKNJK8lPQ7pPwiY)

You can use it, but it's not very convenient.

If you want to test the flux lora, i suggest using cubiq's [flux sampler params](https://github.com/cubiq/ComfyUI_essentials).

**Comment by ondrovic** [comment]
Okay guess I will look at essentials then thanks
