### ISSUE TITLE
想使用unet文件夹下的模型应该怎么做

### ISSUE THREAD

**Issue by excavate** [yolain/ComfyUI-Yolain-Workflows#12]
如题，flux的模型有很多都位于unet文件夹下，如何在这些工作流中使用它们

**Comment by yolain** [comment]
![flux](https://github.com/user-attachments/assets/c554b806-fa79-49a1-b578-1e38ec6f5aba)
酱紫。fluxloader里的 ckpt_name 随遍选一个，会跳过加载器上的模型加载。

**Comment by excavate** [comment]
> ![flux](https://private-user-images.githubusercontent.com/73304135/386297356-c554b806-fa79-49a1-b578-1e38ec6f5aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Mzc0MjIsIm5iZiI6MTczMTYzNzEyMiwicGF0aCI6Ii83MzMwNDEzNS8zODYyOTczNTYtYzU1NGI4MDYtZmE3OS00OWExLWI1NzgtMWUzOGVjNmY1YWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjVmZmFmNTc4ODVhMDg4ODBlMmExNjMxMDZhYjBlZDhmNDc1YWZkNzAxZjM2M2Y5MTUyMjk0ODRkNWI4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ADPfKPKmubCAV9RzEhno9XHgGY7NuTAbiPXxzJkameg) 酱紫。fluxloader里的 ckpt_name 随遍选一个，会跳过加载器上的模型加载。




可以把关于flux的工作流也放上来吗？这样就可以直接跑了，谢谢你

**Comment by yolain** [comment]
> > ![flux](https://private-user-images.githubusercontent.com/73304135/386297356-c554b806-fa79-49a1-b578-1e38ec6f5aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Mzc0MjIsIm5iZiI6MTczMTYzNzEyMiwicGF0aCI6Ii83MzMwNDEzNS8zODYyOTczNTYtYzU1NGI4MDYtZmE3OS00OWExLWI1NzgtMWUzOGVjNmY1YWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjVmZmFmNTc4ODVhMDg4ODBlMmExNjMxMDZhYjBlZDhmNDc1YWZkNzAxZjM2M2Y5MTUyMjk0ODRkNWI4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ADPfKPKmubCAV9RzEhno9XHgGY7NuTAbiPXxzJkameg) 酱紫。fluxloader里的 ckpt_name 随遍选一个，会跳过加载器上的模型加载。
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 可以把关于flux的工作流也放上来吗？这样就可以直接跑了，谢谢你

那个图片应该拖进去 就是工作流

**Comment by excavate** [comment]
> > > ![flux](https://private-user-images.githubusercontent.com/73304135/386297356-c554b806-fa79-49a1-b578-1e38ec6f5aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Mzc0MjIsIm5iZiI6MTczMTYzNzEyMiwicGF0aCI6Ii83MzMwNDEzNS8zODYyOTczNTYtYzU1NGI4MDYtZmE3OS00OWExLWI1NzgtMWUzOGVjNmY1YWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjVmZmFmNTc4ODVhMDg4ODBlMmExNjMxMDZhYjBlZDhmNDc1YWZkNzAxZjM2M2Y5MTUyMjk0ODRkNWI4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ADPfKPKmubCAV9RzEhno9XHgGY7NuTAbiPXxzJkameg) 酱紫。fluxloader里的 ckpt_name 随遍选一个，会跳过加载器上的模型加载。
> > 
> > 
> > 可以把关于flux的工作流也放上来吗？这样就可以直接跑了，谢谢你
> 
> 那个图片应该拖进去 就是工作流

好的，我跑了文生图的工作流和网上找到的另一个文生图工作流，发现两者在种子相同的情况下出图很不一样，为什么？
![image](https://github.com/user-attachments/assets/7cf5b48c-fc83-4ded-a991-f9769b98043f)
[1-1基础文生图_flux.json](https://github.com/user-attachments/files/17770551/1-1._flux.json)

**Comment by yolain** [comment]
cfg。。 下面是3.5呀 。上面只有1

**Comment by excavate** [comment]
> cfg。。 下面是3.5呀 。上面只有1

好的好的，谢谢！调整后一样了
